trainer:
  max_epochs: 150                   
  log_every_n_steps: 5
  accelerator: cpu                  
  devices: 1
  default_root_dir: logs/Morocco-FTW-Filtered  # Updated to indicate filtered data
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        mode: min
        save_top_k: 3
        save_last: true
        filename: "{epoch}-{val_loss:.2f}"
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        patience: 5                
        mode: min

model:
  class_path: ftw.trainers.CustomSemanticSegmentationTask
  init_args:
    class_weights: [0.0, 1.165, 1.835]  
    loss: "ce" 
    model: "unet"
    backbone: "efficientnet-b3"
    weights: true                   
    patch_weights: false
    in_channels: 8                  
    num_classes: 3                  
    num_filters: 64
    ignore_index: 0
    lr: 0.0001                  #1e-4                       
    patience: 100
    # Add regularization
    #dropout_rate: 0.3  # Add dropout 
    #weight_decay: 0.01  # L2 regularization

data:
  class_path: ftw.datamodules.FTWDataModule
  init_args:
    batch_size: 2                  
    num_workers: 0                
    train_countries:
      - morocco
    val_countries:
      - morocco  
    test_countries:
      - morocco
    temporal_options: "stacked"     
    load_boundaries: true
              
  dict_kwargs:
    root: "C:/Users/qin.xu/github/ftw-baselines/data/ftw"

seed_everything: 42